### ISSUE TITLE
[Just a suggestion] add README

### ISSUE THREAD

**Issue by MartinaRuocco** [abhishekkrthakur/melanoma-deep-learning#1]
Hey there!
May I suggest you add a README file with the link to your [youtube video](https://youtu.be/Kzrfw-tAZew)? I found it very informative :)
This way people can star your repo on github and always have access to the explanation!
Thank you!

**Comment by Kesavan13** [comment]
Traceback (most recent call last):
  File "api.py", line 99, in <module>
    MODEL.load_state_dict(torch.load("model.bin"))
  File "/home/kesav/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/kesav/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

What can I do to run the api.py ??
